"""Curated generational meme catalog representing internet culture eras."""

from __future__ import annotations

import time
from typing import List
from app.models.meme import MediaType, NormalizedMeme, SourcePlatform

NOW = time.time()

INITIAL_GENERATIONAL_MEMES: List[dict] = [
    # -------------------------------------------------------------
    # GEN ALPHA (Brainrot, Skibidi, Ohio, Rizz, Fanum Tax)
    # -------------------------------------------------------------
    {
        "id": "gen_alpha_1",
        "title": "When the teacher leaves the room and the Skibidi Toilet Ohio energy takes over",
        "media_url": "https://api.memegen.link/images/fine.jpg",
        "media_type": MediaType.IMAGE,
        "source_platform": SourcePlatform.REDDIT,
        "source_community": "r/GenAlpha",
        "permalink": "https://reddit.com/r/GenAlpha",
        "author": "u/RizzMaster9000",
        "score": 38400,
        "num_comments": 1420,
        "created_at": NOW - 1200,
        "generation": "gen_alpha",
        "trending_score": 98.6,
    },
    {
        "id": "gen_alpha_2",
        "title": "Baby Gronk just Fanum taxed my lunch at the Ohio cafeteria, no cap",
        "media_url": "https://api.memegen.link/images/doge.jpg",
        "media_type": MediaType.IMAGE,
        "source_platform": SourcePlatform.REDDIT,
        "source_community": "r/GenAlpha",
        "permalink": "https://reddit.com/r/GenAlpha",
        "author": "u/GyattInspector",
        "score": 29100,
        "num_comments": 890,
        "created_at": NOW - 3600,
        "generation": "gen_alpha",
        "trending_score": 94.2,
    },
    {
        "id": "gen_alpha_3",
        "title": "Me maintaining my 240-day mewing streak during the entire math exam",
        "media_url": "https://api.memegen.link/images/cheems.jpg",
        "media_type": MediaType.IMAGE,
        "source_platform": SourcePlatform.REDDIT,
        "source_community": "r/skibiditoilet",
        "permalink": "https://reddit.com/r/skibiditoilet",
        "author": "u/SigmaGrindset101",
        "score": 21500,
        "num_comments": 540,
        "created_at": NOW - 7200,
        "generation": "gen_alpha",
        "trending_score": 89.4,
    },
    {
        "id": "gen_alpha_4",
        "title": "Kai Cenat seeing Grimace Shake memes still appearing on his FYP in 2026",
        "media_url": "https://api.memegen.link/images/rollsafe.jpg",
        "media_type": MediaType.IMAGE,
        "source_platform": SourcePlatform.REDDIT,
        "source_community": "r/GenAlpha",
        "permalink": "https://reddit.com/r/GenAlpha",
        "author": "u/LivvyDunneRizz",
        "score": 19400,
        "num_comments": 412,
        "created_at": NOW - 9400,
        "generation": "gen_alpha",
        "trending_score": 86.1,
    },

    # -------------------------------------------------------------
    # GEN Z (Post-Irony, Wojak, Barbenheimer, Goofy Ahh, Surreal)
    # -------------------------------------------------------------
    {
        "id": "gen_z_1",
        "title": "Wojak explaining to his parents why he invested his college tuition into AI meme coins",
        "media_url": "https://api.memegen.link/images/drake.jpg",
        "media_type": MediaType.IMAGE,
        "source_platform": SourcePlatform.REDDIT,
        "source_community": "r/dankmemes",
        "permalink": "https://reddit.com/r/dankmemes",
        "author": "u/DoomerWojak",
        "score": 42000,
        "num_comments": 1650,
        "created_at": NOW - 2400,
        "generation": "gen_z",
        "trending_score": 99.4,
    },
    {
        "id": "gen_z_2",
        "title": "Chad GigaChad developer writing the entire production backend in assembly over the weekend",
        "media_url": "https://api.memegen.link/images/fine.jpg",
        "media_type": MediaType.IMAGE,
        "source_platform": SourcePlatform.REDDIT,
        "source_community": "r/me_irl",
        "permalink": "https://reddit.com/r/me_irl",
        "author": "u/GigaDev",
        "score": 34800,
        "num_comments": 920,
        "created_at": NOW - 4800,
        "generation": "gen_z",
        "trending_score": 95.8,
    },
    {
        "id": "gen_z_3",
        "title": "Barbenheimer anniversary — when you watch existential dread right after pink sunshine",
        "media_url": "https://api.memegen.link/images/distracted.jpg",
        "media_type": MediaType.IMAGE,
        "source_platform": SourcePlatform.KNOWYOURMEME,
        "source_community": "trending",
        "permalink": "https://knowyourmeme.com/memes/barbenheimer",
        "author": "u/PopCultureWatcher",
        "score": 26700,
        "num_comments": 680,
        "created_at": NOW - 8200,
        "generation": "gen_z",
        "trending_score": 91.0,
    },
    {
        "id": "gen_z_4",
        "title": "NPC coworker repeating the exact same weather observation every morning at 8:59 AM",
        "media_url": "https://api.memegen.link/images/doge.jpg",
        "media_type": MediaType.IMAGE,
        "source_platform": SourcePlatform.REDDIT,
        "source_community": "r/dankmemes",
        "permalink": "https://reddit.com/r/dankmemes",
        "author": "u/BruhMomentum",
        "score": 22100,
        "num_comments": 510,
        "created_at": NOW - 11000,
        "generation": "gen_z",
        "trending_score": 87.5,
    },

    # -------------------------------------------------------------
    # MILLENNIAL (Classic Internet, Advice Animals, Doge, Rage)
    # -------------------------------------------------------------
    {
        "id": "millennial_1",
        "title": "Distracted Boyfriend — Shiny New Javascript Framework vs The Battle-Tested Monolith",
        "media_url": "https://api.memegen.link/images/distracted.jpg",
        "media_type": MediaType.IMAGE,
        "source_platform": SourcePlatform.KNOWYOURMEME,
        "source_community": "confirmed",
        "permalink": "https://knowyourmeme.com/memes/distracted-boyfriend",
        "author": "u/SeniorStaffDev",
        "score": 51200,
        "num_comments": 2100,
        "created_at": NOW - 3000,
        "generation": "millennial",
        "trending_score": 97.8,
    },
    {
        "id": "millennial_2",
        "title": "Much Code. Very Refactor. Such Pull Request. Wow. Doge approved.",
        "media_url": "https://api.memegen.link/images/doge.jpg",
        "media_type": MediaType.IMAGE,
        "source_platform": SourcePlatform.REDDIT,
        "source_community": "r/AdviceAnimals",
        "permalink": "https://reddit.com/r/AdviceAnimals",
        "author": "u/DogeOG",
        "score": 45600,
        "num_comments": 1340,
        "created_at": NOW - 5400,
        "generation": "millennial",
        "trending_score": 93.9,
    },
    {
        "id": "millennial_3",
        "title": "Drake Hotline Bling: Testing in Staging (Dislike) vs Direct to Production on Friday (Like)",
        "media_url": "https://api.memegen.link/images/drake.jpg",
        "media_type": MediaType.IMAGE,
        "source_platform": SourcePlatform.REDDIT,
        "source_community": "r/memes",
        "permalink": "https://reddit.com/r/memes",
        "author": "u/YoloDeployer",
        "score": 38900,
        "num_comments": 870,
        "created_at": NOW - 9000,
        "generation": "millennial",
        "trending_score": 90.1,
    },
    {
        "id": "millennial_4",
        "title": "Bad Luck Brian — Writes unit test to ensure zero bugs, test suite catches 140 new ones",
        "media_url": "https://api.memegen.link/images/rollsafe.jpg",
        "media_type": MediaType.IMAGE,
        "source_platform": SourcePlatform.REDDIT,
        "source_community": "r/AdviceAnimals",
        "permalink": "https://reddit.com/r/AdviceAnimals",
        "author": "u/BrianTheUnlucky",
        "score": 28400,
        "num_comments": 610,
        "created_at": NOW - 12500,
        "generation": "millennial",
        "trending_score": 85.0,
    },

    # -------------------------------------------------------------
    # GEN X / BOOMER (Minions, LOLCats, Dancing Baby, Demotivational)
    # -------------------------------------------------------------
    {
        "id": "gen_x_1",
        "title": "Don't speak to me until my second pot of coffee has had its own cup of coffee",
        "media_url": "https://api.memegen.link/images/cheems.jpg",
        "media_type": MediaType.IMAGE,
        "source_platform": SourcePlatform.REDDIT,
        "source_community": "r/wholesomememes",
        "permalink": "https://reddit.com/r/wholesomememes",
        "author": "u/CoffeeGrandpa",
        "score": 31200,
        "num_comments": 740,
        "created_at": NOW - 6200,
        "generation": "gen_x",
        "trending_score": 92.5,
    },
    {
        "id": "gen_x_2",
        "title": "I Can Haz Cheezburger — Ancient text discovered from the dawn of internet lore",
        "media_url": "https://api.memegen.link/images/fine.jpg",
        "media_type": MediaType.IMAGE,
        "source_platform": SourcePlatform.KNOWYOURMEME,
        "source_community": "confirmed",
        "permalink": "https://knowyourmeme.com/memes/happy-cat",
        "author": "u/Web1Historian",
        "score": 27800,
        "num_comments": 630,
        "created_at": NOW - 10500,
        "generation": "gen_x",
        "trending_score": 88.3,
    },
    {
        "id": "gen_x_3",
        "title": "All Your Base Are Belong To Us — For great justice, make your time",
        "media_url": "https://api.memegen.link/images/doge.jpg",
        "media_type": MediaType.IMAGE,
        "source_platform": SourcePlatform.KNOWYOURMEME,
        "source_community": "confirmed",
        "permalink": "https://knowyourmeme.com/memes/all-your-base-are-belong-to-us",
        "author": "u/RetroCaptain",
        "score": 23400,
        "num_comments": 490,
        "created_at": NOW - 14000,
        "generation": "gen_x",
        "trending_score": 83.7,
    },
]


def get_initial_generational_memes() -> List[NormalizedMeme]:
    """Return normalized instances of the curated generational catalog."""
    return [NormalizedMeme(**item) for item in INITIAL_GENERATIONAL_MEMES]
